### ISSUE TITLE
Add unescape?

### ISSUE THREAD

**Issue by kaploink** [joliss/js-string-escape#3]
Hi, any chance of adding unescape functionality to go back the other way?  E.g. to convert double escaped to single escaped.

Cheers
Matt

**Comment by mathiasbynens** [comment]
That sounds like an oddball use case to me. Is this a real problem you’re having or just a theoretical one?

**Comment by joliss** [comment]
I think parsing arbitrary JavaScript string literals is a bit too [complex](https://github.com/marijnh/acorn/blob/af5f7cf4b8e76fe5b157cb0a8adfbcf138564f18/src/tokenize.js#L527) to add it to this module, but you could create a new module that does it. Or maybe in practice you might call a JavaScript tokenizer (like Acorn's or Esprima's) and see if you get a StringLiteral token back.

**Comment by kaploink** [comment]
Our use case is indeed a bit oddball, but would've thought the general need to go in reverse would be common.  Similar to encode/decode, serialize/deserialize.  We do have a working solution, just seems better suited to a generic lib.

In our case we're receiving json through an ad middleware layer that converts everything to document.writeLns...  The serialisation to string is already done (as per same standard rules this lib follows), we just need to convert back.

Here's what we receive 

```javascript
"document.writeln("{");
document.writeln("\"title\": \"Get Car Insurance\",");
document.writeln("\"subtitle\": \"Find the insurance package to suit you.\",");
document.writeln("\"link\": \"http://crtl.aimatch.com/carsales/adclick/FCID=211227/site=cs.home/area=home…hod=get/size=186x90/tile=14/random=5628910930/viewid=606140082/relocate=/\",");
document.writeln("\"logoimage\": \"http://content.aimatch.com/carsales/IAG/nrma_logo.png\",");
document.writeln("\"creativeimage\": \"http://content.aimatch.com/carsales/IAG/nrma_photo.jpg\",");
document.writeln("\"script\": \"<script src=\\\"http://cdn.doubleverify.com/dvtp_src.js?ctx=777690&cmp=186019&sid=Mediamotive AU&plc=3607056&num=&adid=&advid=963532&adsrv=115&region=30&btreg=&btadsrv=&crt=&crtname=&chnl=&unit=&pid=&uid=&dvtagver=6.1.src\\\" type=\\\"text/javascript\\\"></script>\"");
document.writeln("}");
"
```

After pulling out the actual strings, we run a couple of regex replaces to unescape the \'s and "'s.  These are the exact opposite of the escape ones this lib does (but less complete), hence why seemed like a good fit.

```javascript
  newContent = newContent.replace(/\\\\/gmi, '\\');
  newContent = newContent.replace(/\\"/gmi, '"'); 
```

...which gives this result:

```json
{  
  "title":"Get Car Insurance",
  "subtitle":"Find the insurance package to suit you.",
  "link":"http://crtl.aimatch.com/carsales/adclick/FCID=211227/site=cs.home/area=home…thod=get/size=186x90/tile=14/random=5628910930/viewid=606140082/relocate=/",
  "logoimage":"http://content.aimatch.com/carsales/IAG/nrma_logo.png",
  "creativeimage":"http://content.aimatch.com/carsales/IAG/nrma_photo.jpg",
  "script":"<script src=\"http://cdn.doubleverify.com/dvtp_src.js?ctx=777690&cmp=186019&sid=Mediamotive AU&plc=3607056&num=&adid=&advid=963532&adsrv=115&region=30&btreg=&btadsrv=&crt=&crtname=&chnl=&unit=&pid=&uid=&dvtagver=6.1.src\" type=\"text/javascript\"></script>"
}
```
